name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # - name: Restore dependencies
    #   # run: dotnet restore MiklosLinkedList/MiklosLinkedList/MiklosLinkedList.csproj
    - name: Install package
      run: sudo apt-get install -y mono-complete
    - name: Build
      run: sudo mcs -out:main.exe BinaryTree.cs Node.cs Recipes.cs Spice.cs Vegetable.cs main.cs main13-45.cs maino.cs Player.cs
    - name: Test
      run: sudo mono main.exe
    # - name: Build
    #   run: dotnet build  MiklosLinkedList/MiklosLinkedList/MiklosLinkedList.csproj --no-restore
    # - name: Test
    #   run: dotnet test MiklosLinkedList/MiklosLinkedList/MiklosLinkedList.csproj --no-build --verbosity normal
