name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # - name: Restore dependencies
    #   # run: dotnet restore MiklosLinkedList/MiklosLinkedList/MiklosLinkedList.csproj
    - name: Install package
      run: sudo apt-get install -y apache2
    - name: Build
      run: dotnet build  MiklosLinkedList/MiklosLinkedList/MiklosLinkedList.csproj --no-restore
    - name: Test
      run: dotnet test MiklosLinkedList/MiklosLinkedList/MiklosLinkedList.csproj --no-build --verbosity normal
